Some usability improvements, in particular better diagnostics for common setup errors.
In pump script:
  - If DISTCC_HOSTS is set, print out a message saying how many hosts
    there are (similar to the one that we already print if you instead
    set DISTCC_POTENTIAL_HOSTS) and how many of them have pump enabled.
  - Report an error if you run pump using a host list containing no
    hosts with ',cpp'.  (Should this be a warning instead?)
  - Report an error if you run pump using an empty host list.
    (Should this be a warning instead?)

In distcc client:
  - Improve the warning messages that you get if you run distcc using
    hosts with ",cpp" without running pump.

diff --git a/pump.in b/pump.in
--- a/pump.in
+++ b/pump.in
@@ -402,6 +402,27 @@ StartIncludeServerAndDetermineHosts() {
               "\"\$HOME/.distcc/hosts\", or \"/etc/distcc/hosts\"." \
               1>&2
       exit 1
+    else
+      hosts=`distcc --show-hosts`
+      num_hosts=`echo "$hosts" | wc -l`
+      num_pump_hosts=`echo "$hosts" | grep ',cpp' | wc -l`
+      if [ $num_hosts -eq 0 ]; then
+        echo "$program_name: error: distcc hosts list is empty!" 1>&2
+        exit 1
+      elif [ $num_pump_hosts -eq 0 ]; then
+        echo "$program_name: error: pump mode requested, but distcc" \
+          "hosts list does not contain any hosts with ',cpp' option" 1>&2
+        exit 1
+      else
+        if [ "$verbose" = 1 ]; then
+          if [ $num_hosts -eq $num_pump_hosts ]; then
+            echo "__________Using $num_hosts distcc servers in pump mode"
+          else
+            echo "__________Using $num_hosts distcc servers, of which only" \
+                 "$num_pump_hosts support pump mode"
+          fi
+        fi
+      fi
     fi
     StartIncludeServer && include_server_status=0
   fi
