Make install-checks work and a lot of clean-up in regards to the 'checking' targets.
- Remove temporary installation for include server tests. The current scheme
  doesn't make too much sense: when testing a real installation, the include
  server is tested in the separate temporary installation.  

  Instead, we propose to make the installation tests run only the regression
  tests in the 'test' directory, unpumped and pumped.  The include server is now
  tested as part of maintainer-check only, but run out of the source directory,
  except for the C extension module.

- The maintainer-check and the maintainer-install-check now run the integration
  test (test/testdistcc.py) also in pump mode.

- A new script, find_c_extension.sh, is added; it finds the location of the
  shared library. It is used for both running the include server tests and the
  regression tests out of the built (not installed) version of the software. It
  was cut of the 'pump' script, which now has been simplified.

- Reorganize the order of affected targets.  Introduce '###############...' as
  separator between sections of Makefile in a more consistent way.  Make each
  section consistently declare all the phony targets at the beginning of the
  section.

- Introduce DISTCC_INSTALLATION variable to account for the precise location
  of the tested binaries in an installation.

- Add verify-binaries-installcheck target to ensure that binaries are in this
  location.

- Also, this target reports the location to users:

    Make sure all paths below are where you expect them to be:
    **********************************************************
    /home/klarlund/svn-distcc/mybin/installation/bin/distcc
    /home/klarlund/svn-distcc/mybin/installation/bin/distccd
    /home/klarlund/svn-distcc/mybin/installation/bin/distccmon-text
    /home/klarlund/svn-distcc/mybin/installation/bin/lsdistcc
    **********************************************************


- Absolutize a couple of relative directory references before they are passed to
  scripts, because otherwise things won't work with the disciplined approach to
  DISTCC_INSTALLATION.

- Change a randomly generated filename so that it resides in /tmp (in
  c_extensions_test.py) and not inside the build directory tree. Fix up logic
  for filenaming to be more secure. This makes 'make distcheck' pass w/o
  permission problems.

- Make include-server-maintainer-check remove the .out file when test passes.
  This makes 'make distcheck' pass the final test of the clean-out.

- Remove the 'Filtering' of the c_extensions_test output. This filtering was
  necessary in a previous version that printed all output to stdout to reduce
  user confusion.  But now the test results go to intermediate files.  This
  change was forced by the removal of the .out files (above).

REVIEWED: fergus, csilvers.

TESTS: make distcheck
       make maintainer-installcheck
       make include-server-maintainer-check
       make maintainer-check

diff --git a/changes/klarlund/s7r7/trunk/Makefile.in b/changes/klarlund/s7r7/trunk/Makefile.in
--- a/changes/klarlund/s7r7/trunk/Makefile.in
+++ b/changes/klarlund/s7r7/trunk/Makefile.in
@@ -68,12 +68,13 @@ INSTALL_PROGRAM = @INSTALL_PROGRAM@
 INSTALL_DATA = @INSTALL_DATA@
 INSTALL_SCRIPT = @INSTALL_SCRIPT@
 
-DISTCC_INSTALLATION = @bindir@
 PYTHON = @PYTHON@
 # RESTRICTED_PATH contains the locations of 'make', 'sh', 'gcc', and 'python'
 # for use in installation tests.  It does usually not contain the path of the
 # installation software.
 RESTRICTED_PATH = /usr/local/bin:/bin:/usr/bin
+# Change this variable to @bindir@ if installation is not on RESTRICTED_PATH:
+DISTCC_INSTALLATION = $(RESTRICTED_PATH)
 
 dist_files =							\
 	src/config.h.in						\
@@ -747,38 +748,44 @@ single-test: check_programs
 
 # Verify that DISTCC_INSTALLATION contains the expected set of binaries.
 verify-binaries-installcheck:
+	@echo -n "Locating binaries in DISTCC_INSTALLATION="
+	@echo "'$(DISTCC_INSTALLATION)'"
+	@echo -n "To use installation in @bindir@, remake with"
+	@echo " argument 'DISTCC_INSTALLATION=@bindir@'."
+	@echo "Make sure all paths below are where you expect them to be:"
+	@echo "**********************************************************"
 	@for p in $(bin_PROGRAMS); do \
-	  if ! test -x "$(DISTCC_INSTALLATION)/$$p"; then \
-	    echo -n "Binary '$$p' could not be found in"; \
-	    echo " DISTCC_INSTALLATION='$(DISTCC_INSTALLATION)'"; \
+	  if ! PATH="$(DISTCC_INSTALLATION)" `which which` "$$p"; then \
+	    echo "Binary '$$p' could not be found in DISTCC_INSTALLATION."; \
 	    exit 1; \
 	  fi; \
-	done; \
-	echo "Checking binaries in DISTCC_INSTALLATION='$(DISTCC_INSTALLATION)'"
+	done 
+	@echo "**********************************************************"
 
 # Lookup distcc programs to be checked in $(DISTCC_INSTALLATION).  The
 # check_PROGRAMS binaries, however, are to be found in $(builddir).
 distcc-installcheck: $(check_PROGRAMS)
-	PATH="$(DISTCC_INSTALLATION):$(builddir):$(RESTRICTED_PATH)" \
+	PATH="$(DISTCC_INSTALLATION):`cd $(builddir) && pwd`:\
+$(RESTRICTED_PATH)" \
 	  TESTDISTCC_OPTS=$(TESTDISTCC_OPTS) \
 	  $(MAKE) maintainer-check-no-set-path
 
 # Check the installation to see whether pump-mode works.
 pump-installcheck:
 	DISTCC_HOSTS='<invalid>' \
-	  $(DISTCC_INSTALLATION)/pump \
+	  PATH="$(DISTCC_INSTALLATION)" pump \
             $(MAKE) DISTCC_INSTALLATION=$(DISTCC_INSTALLATION) \
 	      RESTRICTED_PATH=$(RESTRICTED_PATH) \
               TESTDISTCC_OPTS=--pump distcc-installcheck; \
 
-# "make maintainer-installcheck" verifies the currently installed version.
-# However, it does not have the "install" target as a dependency so that you can
-# can check an installation that is installed via some different method
-# (e.g. rpm or debian package).  You must specify the location of such an
+# "make maintainer-installcheck" verifies the currently installed version in in
+# RESTRICTED_PATH.  It does not have the "install" target as a dependency so
+# that you can can check an installation that is installed via some different
+# method (e.g. rpm or debian package).  You must specify the location of such an
 # installation by overriding the value of DISTCC_INSTALLATION in the call of
 # make as in:
 #
-#   make DISTCC_INSTALLATION=/usr maintainer-installcheck
+#   make DISTCC_INSTALLATION=/usr/mybin maintainer-installcheck
 #
 # The maintainer-installcheck does not run the include server unit tests;
 # but the integration tests in 'test' are run in pump mode.
