Make install-checks work and a lot of clean-up in regards to the 'checking' targets.
- Remove temporary installation for include server tests. The current scheme
  doesn't make too much sense: when testing a real installation, the include
  server is tested in the separate temporary installation.  

  Instead, we propose to make the installation tests run only the regression
  tests in the 'test' directory, unpumped and pumped.  The include server is now
  tested as part of maintainer-check only, but run out of the source directory,
  except for the C extension module.

- The maintainer-check and the maintainer-install-check now run the integration
  test (test/testdistcc.py) also in pump mode.

- A new script, find_c_extension.sh, is added; it finds the location of the
  shared library. It is used for both running the include server tests and the
  regression tests out of the built (not installed) version of the software. It
  was cut of the 'pump' script, which now has been simplified.

- Reorganize the order of affected targets.  Introduce '###############...' as
  separator between sections of Makefile in a more consistent way.  Make each
  section consistently declare all the phony targets at the beginning of the
  section.

- Introduce DISTCC_INSTALLATION variable to account for the precise location
  of the tested binaries in an installation.

- Add verify-binaries-installcheck target to ensure that binaries are in this
  location.

- Also, this target reports the location to users:

    Make sure all paths below are where you expect them to be:
    **********************************************************
    /home/klarlund/svn-distcc/mybin/installation/bin/distcc
    /home/klarlund/svn-distcc/mybin/installation/bin/distccd
    /home/klarlund/svn-distcc/mybin/installation/bin/distccmon-text
    /home/klarlund/svn-distcc/mybin/installation/bin/lsdistcc
    **********************************************************


- Absolutize a couple of relative directory references before they are passed to
  scripts, because otherwise things won't work with the disciplined approach to
  DISTCC_INSTALLATION.

- Change a randomly generated filename so that it resides in /tmp (in
  c_extensions_test.py) and not inside the build directory tree. Fix up logic
  for filenaming to be more secure. This makes 'make distcheck' pass w/o
  permission problems.  Also, delete the temporary file and directory when
  test passes.

- Make include-server-maintainer-check remove the .out file when test passes.
  This makes 'make distcheck' pass the final test of the clean-out.

- Remove the 'Filtering' of the c_extensions_test output. This filtering was
  necessary in a previous version that printed all output to stdout to reduce
  user confusion.  But now the test results go to intermediate files.  This
  change was forced by the removal of the .out files (above).

REVIEWED: fergus, csilvers.

TESTS: make distcheck
       make maintainer-installcheck
       make include-server-maintainer-check
       make maintainer-check

diff --git a/changes/klarlund/s7r7/trunk/Makefile.in b/changes/klarlund/s7r7/trunk/Makefile.in
--- a/changes/klarlund/s7r7/trunk/Makefile.in
+++ b/changes/klarlund/s7r7/trunk/Makefile.in
@@ -585,7 +585,9 @@ distcheck: dist
 	&& cd +distcheck/$(distdir)/_build \
 	&& ../configure --srcdir=.. --prefix="$$dc_install_base" \
 	&& $(MAKE) && $(MAKE) maintainer-check \
-	&& $(MAKE) install && $(MAKE) maintainer-installcheck \
+	&& $(MAKE) install \
+	&& $(MAKE) DISTCC_INSTALLATION="$$dc_install_base/bin" \
+	        maintainer-installcheck \
 	&& $(MAKE) distclean
 	chmod -R u+w +distcheck
 	test `find +distcheck/$(distdir)/_build -type f -print | wc -l` -eq 0 \
@@ -653,24 +655,14 @@ maintainer-check-no-set-path:
 	@if ! $(PYTHON) -c 'import sys; print sys.version'; then \
 	  echo "WARNING: python not found; tests skipped"; \
 	else \
-	  found=0; \
-	  for d in `echo $(PATH) | tr ':' ' '`; do \
-	     [ -x "$$d/gcc" ] && found=1; \
-	  done; \
-	  if [ $$found = "0" ]; then \
-	    echo -n "Could not find gcc on the restricted path used"; \
-	    echo " to avoid confusion caused by distcc"; \
-	    echo -n "masquerades on the normal path."; \
-	    echo "PATH is currently '$$PATH'.  Please check RESTRICTED_PATH."; \
+	  if ! gcc --version 2>/dev/null; then \
+	    echo "Could not find gcc on the restricted path used to avoid"; \
+	    echo "confusion caused by distcc masquerades on the normal path."; \
+	    echo "PATH is currently '$$PATH'."; \
+	    echo "Please change RESTRICTED_PATH to change this PATH value."; \
 	    exit 1; \
 	  fi; \
-	  path=""; \
-	  for d in `echo $(PATH) | tr ':' ' '`; do \
-	     [ "$$d" = "." ] && d=`pwd`; \
-	     path=$$path:$$d; \
-	  done; \
-	  PATH=$$path \
-	    $(PYTHON) $(srcdir)/test/testdistcc.py $(TESTDISTCC_OPTS); \
+	  $(PYTHON) $(srcdir)/test/testdistcc.py $(TESTDISTCC_OPTS); \
 	fi
 
 distcc-maintainer-check: check_programs
@@ -706,7 +698,7 @@ include-server-maintainer-check: include-server
 pump-maintainer-check: pump include-server check_programs
 	@if [ -d "$(include_server_builddir)" ]; then \
 	  DISTCC_HOSTS='<invalid>' \
-	  DISTCC_SRCDIR=`cd $(srcdir); pwd` \
+	  DISTCC_SRCDIR=`cd $(srcdir) && pwd` \
 	    $(builddir)/pump \
               $(MAKE) \
 	        RESTRICTED_PATH=$(RESTRICTED_PATH) \
@@ -772,8 +764,10 @@ $(RESTRICTED_PATH)" \
 
 # Check the installation to see whether pump-mode works.
 pump-installcheck:
+	which_loc=`which which`; \
+	pump_loc=`PATH="$(DISTCC_INSTALLATION)" $$which_loc pump`; \
 	DISTCC_HOSTS='<invalid>' \
-	  PATH="$(DISTCC_INSTALLATION)" pump \
+	  $$pump_loc \
             $(MAKE) DISTCC_INSTALLATION=$(DISTCC_INSTALLATION) \
 	      RESTRICTED_PATH=$(RESTRICTED_PATH) \
               TESTDISTCC_OPTS=--pump distcc-installcheck; \
@@ -782,10 +776,7 @@ pump-installcheck:
 # RESTRICTED_PATH.  It does not have the "install" target as a dependency so
 # that you can can check an installation that is installed via some different
 # method (e.g. rpm or debian package).  You must specify the location of such an
-# installation by overriding the value of DISTCC_INSTALLATION in the call of
-# make as in:
-#
-#   make DISTCC_INSTALLATION=/usr/mybin maintainer-installcheck
+# installation by overriding the value of DISTCC_INSTALLATION.
 #
 # The maintainer-installcheck does not run the include server unit tests;
 # but the integration tests in 'test' are run in pump mode.
